apiVersion: 1.0.0
kind: Plugin
metadata:
  name: HCP-RDMS Inventory Sync
  description: SAP HCP Device Sync Plugin for Reekoh IoT Platform
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: InventorySync
  price: 0
  tags:
    - inventory-sync
    - sap
    - hcp
    - rdms
    
  consumerType: pull

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      host:
        label: Host
        type: String
        maxLength: 1000
        required: true
        help: "The SAP-HCP Host to send data to."
      username:
        label: Username
        type: String
        maxLength: 1000
        required: true
        help: "Username to use for API Basic Authentication."
      password:
        label: Password
        type: Password
        maxLength: 1000
        required: true
        help: "Password to use for API Basic Authentication."
      deviceType:
        label: Device Type ID
        type: String
        maxLength: 1000
        required: true
        help: "ID of the device type."
